"""init

Revision ID: 5a69a0d5ecc5
Revises: 
Create Date: 2026-08-18 15:26:47.354366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5a69a0d5ecc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('reference_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('summary', sa.String(length=6000), nullable=False),
    sa.Column('injury_pattern', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('weapon_pattern', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('timeline_pattern', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('spatial_pattern', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('witness_conflict_pattern', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_gap_pattern', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('event_sequence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('conclusion', sa.String(length=2000), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('is_dev', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_owner_id'), 'cases', ['owner_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('input_object_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output_object_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=4000), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('conflict_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('sides', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_case_id'), 'conflicts', ['case_id'], unique=False)
    op.create_table('constraints',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('constraint_id', sa.String(length=32), nullable=False),
    sa.Column('constraint_type', sa.String(length=24), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('expression', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('anchor_id', sa.String(length=64), nullable=False),
    sa.Column('source_evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraints_case_id'), 'constraints', ['case_id'], unique=False)
    op.create_table('discriminating_evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_pair', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('shared_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('differing_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('needed_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discriminating_evidence_case_id'), 'discriminating_evidence', ['case_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_case_id'), 'entities', ['case_id'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('extracted', sa.Boolean(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provider_label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_case_id'), 'evidence_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_item_type'), 'evidence_items', ['item_type'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('fact_id', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.String(length=4000), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('constraint_strength', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('qualifier', sa.String(length=60), nullable=False),
    sa.Column('source_evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_authoritative', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_case_id'), 'facts', ['case_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.String(length=4000), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=False),
    sa.Column('source_evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_case_id'), 'findings', ['case_id'], unique=False)
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_table('forensic_anchors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('anchor_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('normalized', sa.String(length=500), nullable=False),
    sa.Column('source_evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forensic_anchors_case_id'), 'forensic_anchors', ['case_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.String(length=6000), nullable=False),
    sa.Column('generation_round', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=False),
    sa.Column('parent_hypothesis_id', sa.String(length=64), nullable=False),
    sa.Column('similar_case_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('similar_case_patterns_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_case_id'), 'hypotheses', ['case_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_case_id'), 'jobs', ['case_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('scenario_comparisons',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_comparisons_case_id'), 'scenario_comparisons', ['case_id'], unique=False)
    op.create_table('similar_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=False),
    sa.Column('reference_label', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('relevant_patterns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('relevance', sa.String(length=60), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['reference_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_similar_cases_case_id'), 'similar_cases', ['case_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('time_type', sa.String(length=24), nullable=False),
    sa.Column('time_start', sa.String(length=60), nullable=False),
    sa.Column('time_end', sa.String(length=60), nullable=False),
    sa.Column('time_label', sa.String(length=120), nullable=False),
    sa.Column('certainty', sa.String(length=24), nullable=False),
    sa.Column('ordering_index', sa.Integer(), nullable=False),
    sa.Column('linked_fact_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('location_entity_id', sa.String(length=64), nullable=False),
    sa.Column('participants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_case_id'), 'timeline_events', ['case_id'], unique=False)
    op.create_table('audio_assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_item_id', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=False),
    sa.Column('speakers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('acoustic_events', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_case_id'), 'audio_assets', ['case_id'], unique=False)
    op.create_index(op.f('ix_audio_assets_evidence_item_id'), 'audio_assets', ['evidence_item_id'], unique=False)
    op.create_table('document_assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_item_id', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('extracted_text_path', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_assets_case_id'), 'document_assets', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_assets_evidence_item_id'), 'document_assets', ['evidence_item_id'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('source_entity_id', sa.String(length=64), nullable=False),
    sa.Column('target_entity_id', sa.String(length=64), nullable=False),
    sa.Column('relation_type', sa.String(length=40), nullable=False),
    sa.Column('evidence_links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relationships_case_id'), 'entity_relationships', ['case_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_relation_type'), 'entity_relationships', ['relation_type'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_entity_id'), 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_target_entity_id'), 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_case_id'), 'events', ['case_id'], unique=False)
    op.create_index(op.f('ix_events_entity_id'), 'events', ['entity_id'], unique=False)
    op.create_table('evidence_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_item_id', sa.String(length=64), nullable=False),
    sa.Column('fact_id', sa.String(length=64), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=200), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('timestamp_seconds', sa.Float(), nullable=True),
    sa.Column('frame', sa.Integer(), nullable=True),
    sa.Column('region', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('speaker', sa.String(length=200), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_sources_case_id'), 'evidence_sources', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_sources_evidence_item_id'), 'evidence_sources', ['evidence_item_id'], unique=False)
    op.create_index(op.f('ix_evidence_sources_fact_id'), 'evidence_sources', ['fact_id'], unique=False)
    op.create_table('image_assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_item_id', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('detected_objects', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('exif', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_assets_case_id'), 'image_assets', ['case_id'], unique=False)
    op.create_index(op.f('ix_image_assets_evidence_item_id'), 'image_assets', ['evidence_item_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('camera_coverage', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_case_id'), 'locations', ['case_id'], unique=False)
    op.create_index(op.f('ix_locations_entity_id'), 'locations', ['entity_id'], unique=False)
    op.create_table('objects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_case_id'), 'objects', ['case_id'], unique=False)
    op.create_index(op.f('ix_objects_entity_id'), 'objects', ['entity_id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_case_id'), 'persons', ['case_id'], unique=False)
    op.create_index(op.f('ix_persons_entity_id'), 'persons', ['entity_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.String(length=6000), nullable=False),
    sa.Column('cause_claim', sa.String(length=1000), nullable=False),
    sa.Column('participants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=4000), nullable=False),
    sa.Column('final_verdict', sa.String(length=2000), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('is_survivor', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_case_id'), 'scenarios', ['case_id'], unique=False)
    op.create_index(op.f('ix_scenarios_is_survivor'), 'scenarios', ['is_survivor'], unique=False)
    op.create_index(op.f('ix_scenarios_status'), 'scenarios', ['status'], unique=False)
    op.create_table('video_assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_item_id', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('scene_changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('camera_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_assets_case_id'), 'video_assets', ['case_id'], unique=False)
    op.create_index(op.f('ix_video_assets_evidence_item_id'), 'video_assets', ['evidence_item_id'], unique=False)
    op.create_table('scenario_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('event_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('linked_fact_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('timing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_events_case_id'), 'scenario_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_scenario_events_scenario_id'), 'scenario_events', ['scenario_id'], unique=False)
    op.create_table('scenario_evidence_links',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_item_id', sa.String(length=64), nullable=False),
    sa.Column('link_type', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.String(length=1000), nullable=False),
    sa.Column('fact_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_evidence_links_case_id'), 'scenario_evidence_links', ['case_id'], unique=False)
    op.create_index(op.f('ix_scenario_evidence_links_evidence_item_id'), 'scenario_evidence_links', ['evidence_item_id'], unique=False)
    op.create_index(op.f('ix_scenario_evidence_links_scenario_id'), 'scenario_evidence_links', ['scenario_id'], unique=False)
    op.create_table('scenario_scores',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_scores_scenario_id'), 'scenario_scores', ['scenario_id'], unique=False)
    op.create_table('video_scenario_specs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('visual_prompt', sa.String(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_scenario_specs_case_id'), 'video_scenario_specs', ['case_id'], unique=False)
    op.create_index(op.f('ix_video_scenario_specs_scenario_id'), 'video_scenario_specs', ['scenario_id'], unique=False)
    op.create_table('generated_videos',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('spec_id', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('video_path', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=1000), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('label_text', sa.String(length=500), nullable=False),
    sa.Column('prompt_used', sa.String(), nullable=False),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['video_scenario_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_videos_case_id'), 'generated_videos', ['case_id'], unique=False)
    op.create_index(op.f('ix_generated_videos_scenario_id'), 'generated_videos', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_generated_videos_spec_id'), 'generated_videos', ['spec_id'], unique=False)
    op.create_table('video_shots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('spec_id', sa.String(length=64), nullable=False),
    sa.Column('shot_index', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('prompt_fragment', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spec_id'], ['video_scenario_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_shots_spec_id'), 'video_shots', ['spec_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_shots_spec_id'), table_name='video_shots')
    op.drop_table('video_shots')
    op.drop_index(op.f('ix_generated_videos_spec_id'), table_name='generated_videos')
    op.drop_index(op.f('ix_generated_videos_scenario_id'), table_name='generated_videos')
    op.drop_index(op.f('ix_generated_videos_case_id'), table_name='generated_videos')
    op.drop_table('generated_videos')
    op.drop_index(op.f('ix_video_scenario_specs_scenario_id'), table_name='video_scenario_specs')
    op.drop_index(op.f('ix_video_scenario_specs_case_id'), table_name='video_scenario_specs')
    op.drop_table('video_scenario_specs')
    op.drop_index(op.f('ix_scenario_scores_scenario_id'), table_name='scenario_scores')
    op.drop_table('scenario_scores')
    op.drop_index(op.f('ix_scenario_evidence_links_scenario_id'), table_name='scenario_evidence_links')
    op.drop_index(op.f('ix_scenario_evidence_links_evidence_item_id'), table_name='scenario_evidence_links')
    op.drop_index(op.f('ix_scenario_evidence_links_case_id'), table_name='scenario_evidence_links')
    op.drop_table('scenario_evidence_links')
    op.drop_index(op.f('ix_scenario_events_scenario_id'), table_name='scenario_events')
    op.drop_index(op.f('ix_scenario_events_case_id'), table_name='scenario_events')
    op.drop_table('scenario_events')
    op.drop_index(op.f('ix_video_assets_evidence_item_id'), table_name='video_assets')
    op.drop_index(op.f('ix_video_assets_case_id'), table_name='video_assets')
    op.drop_table('video_assets')
    op.drop_index(op.f('ix_scenarios_status'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_is_survivor'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_case_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_persons_entity_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_case_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_objects_entity_id'), table_name='objects')
    op.drop_index(op.f('ix_objects_case_id'), table_name='objects')
    op.drop_table('objects')
    op.drop_index(op.f('ix_locations_entity_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_case_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_image_assets_evidence_item_id'), table_name='image_assets')
    op.drop_index(op.f('ix_image_assets_case_id'), table_name='image_assets')
    op.drop_table('image_assets')
    op.drop_index(op.f('ix_evidence_sources_fact_id'), table_name='evidence_sources')
    op.drop_index(op.f('ix_evidence_sources_evidence_item_id'), table_name='evidence_sources')
    op.drop_index(op.f('ix_evidence_sources_case_id'), table_name='evidence_sources')
    op.drop_table('evidence_sources')
    op.drop_index(op.f('ix_events_entity_id'), table_name='events')
    op.drop_index(op.f('ix_events_case_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_entity_relationships_target_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_relation_type'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_case_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_document_assets_evidence_item_id'), table_name='document_assets')
    op.drop_index(op.f('ix_document_assets_case_id'), table_name='document_assets')
    op.drop_table('document_assets')
    op.drop_index(op.f('ix_audio_assets_evidence_item_id'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_case_id'), table_name='audio_assets')
    op.drop_table('audio_assets')
    op.drop_index(op.f('ix_timeline_events_case_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_similar_cases_case_id'), table_name='similar_cases')
    op.drop_table('similar_cases')
    op.drop_index(op.f('ix_scenario_comparisons_case_id'), table_name='scenario_comparisons')
    op.drop_table('scenario_comparisons')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_case_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_hypotheses_case_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_forensic_anchors_case_id'), table_name='forensic_anchors')
    op.drop_table('forensic_anchors')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_index(op.f('ix_findings_case_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_facts_case_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_evidence_items_item_type'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_case_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_case_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_discriminating_evidence_case_id'), table_name='discriminating_evidence')
    op.drop_table('discriminating_evidence')
    op.drop_index(op.f('ix_constraints_case_id'), table_name='constraints')
    op.drop_table('constraints')
    op.drop_index(op.f('ix_conflicts_case_id'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_cases_owner_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reference_cases')
    # ### end Alembic commands ###