"""Object/file storage port."""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class StoragePort(Protocol):
    """Provider-independent blob storage port."""

    def save(self, case_id: str, evidence_id: str, filename: str, data: bytes) -> str: ...
    def load(self, path: str) -> bytes | None: ...
    def exists(self, path: str) -> bool: ...
    def delete(self, path: str) -> None: ...
    def label(self) -> str: ...
